
variables:
  names:  # order matter! must match order received by `evalaute`
    - 'itr'
    - 'T'
    - 'N'
    - 'beta'
    - 'r'
    
  itr:
    type: 'int_range'
    min: 1
    max: 100

  r: 
    type: 'range'
    min: 0
    max: 1.2
    length: 13

  beta:
    type: 'list'
    values: 
      - .45
      - .5
      - .6
      - .7
      - .8
      - .9
      - .95

  T: 
    type: 'list'
    values:
      - 2000

  N:
    type: 'list'
    values:
      - 1000
